FROM pandoc/core:latest-ubuntu

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-cffi \
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf2.0-0 \
    libffi-dev \
    shared-mime-info \
    pdftk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install WeasyPrint
